# This is a basic workflow to help you get started with Actions

name: Build V8 for Apple

# Controls when the action will run. 
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Set Xcode
        run: sudo xcode-select -switch "/Applications/Xcode_12.app"
      
      # Runs a single command using the runners shell
      - name: Run build v8 script
        run: |
          cd $GITHUB_WORKSPACE/V8
          chmod 755 build_v8_apple.sh
          ./build_v8_apple.sh
      - uses: actions/upload-artifact@v2 
        with:
          name: v8_apple
          path: V8/build/targets
