# This is a basic workflow to help you get started with Actions

name: Build ClearScriptV8 for Android

# Controls when the action will run. 
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on 
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Download V8 Library
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build_v8_android.yml
          name: v8_android
          path: V8/build/targets
          
      - name: Install Android NDK
        run: |
          cd $GITHUB_WORKSPACE
          wget -O NDK -q https://dl.google.com/android/repository/android-ndk-r21b-linux-x86_64.zip
          sudo apt install unzip -y
          unzip -q NDK
          echo "::set-env name=ANDROID_NDK::${GITHUB_WORKSPACE}/android-ndk-r21b"
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true

      # Runs a single command using the runners shell
      - name: Run build ClearScriptV8 script
        run: |
          cd $GITHUB_WORKSPACE/ClearScript.V8.Native/scripts
          chmod 755 make_clearscript_android.sh
          ./make_clearscript_android.sh

      - uses: actions/upload-artifact@v2
        with:
          name: ClearScript.V8.Native
          path: ClearScript.V8.Native/build/targets
